### ISSUE TITLE
Violation of GitHub's Terms of Service

### ISSUE THREAD

**Issue by abe-101** [Vraelot/Justtesting#1]
Be aware that this tool might be in violation of GitHub's Terms of Service.

> In particular, any repositories that use GitHub Actions or similar 3rd party services solely to interact with 3rd party websites, to engage in incentivized activities, or for general computing purposes may fall foul of the [GitHub Additional Product Terms (Actions)](https://docs.github.com/github/site-policy/github-terms-for-additional-products-and-features#actions), or the [GitHub Acceptable Use Policies](https://docs.github.com/github/site-policy/github-acceptable-use-policies).
>     Actions should not be used for any activity unrelated to the production, testing, deployment, or publication of the software project associated with the repository where GitHub Actions are used.
Hence pushing content to Anchor FM from YouTube is a violation of ToS

**Comment by abe-101** [comment]
As a result of this issue I've created a python command line tool that accomplishes the same thing
[tbue-cast](https://github.com/abe-101/tube-castl)

**Comment by Vraelot** [comment]
Oh! Thank you for letting me know! :o
